require('dotenv').config();


export const COMMUNITY_SERVICES_BASE = process.env.REACT_APP_COMMUNITY_SERVICES_BASE || 'http://localhost/';
//export const COMMUNITY_SERVICES_BASE = 'http://13.58.68.184/';
export const COMMUNITY_NEWS_ENDPOINT = COMMUNITY_SERVICES_BASE + (process.env.REACT_APP_COMMUNITY_NEWS_ENDPOINT || 'community/news/');
export const COMMUNITY_SERVICES_TWITTER_ENDPOINT = COMMUNITY_SERVICES_BASE + (process.env.REACT_APP_COMMUNITY_SERVICES_TWITTER_ENDPOINT || 'community/twitter/hashsearch/');
export const COMMUNITY_EVENTS_EVENTBRITE_ENDPOINT = COMMUNITY_SERVICES_BASE + (process.env.REACT_APP_COMMUNITY_EVENTS_EVENTBRITE_ENDPOINT || 'community/events/');
export const COMMUNITY_ADMIN_ENDPOINT = COMMUNITY_SERVICES_BASE + (process.env.REACT_APP_COMMUNITY_ADMIN_ENDPOINT || 'community/admin/');
export const COMMUNITY_WEATHER_ENDPOINT = COMMUNITY_SERVICES_BASE + (process.env.REACT_APP_COMMUNITY_WEATHER_ENDPOINT || 'community/weather/');

export const WEBPAGE_ADMIN = process.env.REACT_APP_WEBPAGE_ADMIN || 'admin_0';
